const express = require('express');
const router = express.Router();
const moviesController = require("../controllers/moviesController");
const { verifyTokenAndAdmin, verifyTokenAndAuthorization } = require('../middleware/verifyToken');
router.post("/movies", verifyTokenAndAdmin, moviesController.createMovie);
router.get("/movies", verifyTokenAndAuthorization, moviesController.getAllMovies);
router.get("/movies/random", verifyTokenAndAuthorization, moviesController.getRandomMovie);
router.get("/movies/:id", verifyTokenAndAuthorization, moviesController.getMovie);
router.put("/movies/:id", verifyTokenAndAdmin, moviesController.updateMovie);
router.delete("/movies/:id", verifyTokenAndAdmin, moviesController.deleteMovie);
module.exports = router;